# Generated by Django 3.2 on 2021-05-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='what_answer',
        ),
    ]
